@MovieWebAPI_HostAddress = http://localhost:5255

GET {{MovieWebAPI_HostAddress}}/weatherforecast/
Accept: application/json



###

GET {{MovieWebAPI_HostAddress}}/movie/
Accept: application/json

##

POST {{MovieWebAPI_HostAddress}}/movie/
Accept: application/json